### ISSUE TITLE
Use vcpkg for FFTW library dependency

### ISSUE THREAD

**Issue by dozius** [dozius/DtBlkFx#6]
The plugin depends on FFTW. It would be nice to be able to download, build and statically link this in a cross platform way. Vcpkg seems like a good option.

**Comment by PaulHaeger** [comment]
How would the workflow look when using Vcpkg ? AFAIK FFTW can also be built using CMake, so you could include it as a sub directory, or just as a CMake dependency. 

A cross platform package manager would make managing build/deploy scripts easier though.

**Comment by dozius** [comment]
Essentially the workflow would be running "vcpkg install [packages]" after cloning. I believe the recommend way to use vcpkg in cmake projects these days is to include it as a submodule, so you wouldn't need to install it separately. This also lends itself nicely to automated build pipelines, something to consider in the future.

There are a couple of reasons specifically to prefer vcpkg for FFTW.

1. There is no official public repository for FFTW to pull in as a submodule. The Github repo for FFTW is actually just the code generator. The source code for the library is only distributed as a tarball on the website.
2. It's been awhile, but the last time I tried to build FFTW it required cross compiling from a linux environment and had a bunch of fiddly configure script voodoo. It was not a smooth process by any means.

Both of these are problems we would need to "roll our own" solution for, or just let vcpkg worry about. I prefer the vcpkg option.

**Comment by PaulHaeger** [comment]
Ok, sounds reasonable. I think in the past I managed to build it on windows using visual studio and cmake but if additional ASM Optimizations are desired the process can get fiddly if I remember correctly.

**Comment by PaulHaeger** [comment]
I created the branch 'vcpkg-fftw' on my fork, added the sub module and added FFTW3 as a dependency. In source builds seem to work on my machine but out of source builds do not. No idea if that is just a problem with my machine or something different.

**Comment by PaulHaeger** [comment]
Ok, seems to work now.

**Comment by dozius** [comment]
Looks fine. Good work!

I do have some small nit picks. If you make a pull request I can make comments on specific lines that need to be touched up before merge.
